# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc34133b528a3f9ef1f6d55d46b7861eb16677b06ada4f12350dcc73f36cc5bde4dd6059f395de63ca90f81b97001d22a2e7cd2bd4bf0ba2d16ebba6678f8539

test:
  secret_key_base: fae8c3c6681f701b3e204be7fd7838c7c142d9cbf72508fbb3bd8735e2be47877cc0795a091625e4b71506b2c3b11e5d4e0d26132051c371fa0c3f6bf9e10232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
